version: '3'
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD
  web:
    image: ghcr.io/microlith57/boop_docker/boop:latest
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./credentials.yml.enc:/usr/src/app/config/credentials.yml.enc
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USERNAME
      - POSTGRES_PASSWORD
      - RAILS_MASTER_KEY
